version: "3"
services:
  db:
    image: mysql:latest
    container_name: mydb
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
      - MYSQL_DATABASE=mysqldb
      - MYSQL_USER=wchuchro
      - MYSQL_PASSWORD=pass123
    ports:
      - 3306:3306
    networks:
      Bridge-Zadanie-1:
        ipv4_address: 10.0.10.3
  javaapp:
    image: java-app
    container_name: myjava
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      Bridge-Zadanie-1:
        ipv4_address: 10.0.10.4

networks:
  Bridge-Zadanie-1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.10.0/24
